# Generated by Django 3.1.7 on 2021-04-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20210409_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson_id',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
    ]
