# Generated by Django 3.1.7 on 2021-04-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20210409_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='course_id',
        ),
    ]
