# Generated by Django 3.1.7 on 2021-04-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20210410_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_content',
            new_name='question_text',
        ),
    ]
